worker_name: jsbox_application
transport_name: jsbox_ussd_registration
javascript_file: go-app-ussd_registration.js
sandbox_id: sandbox1
executable: /usr/bin/node
amqp_prefetch_count: 1

app_context: "{require: function(m) { if (['moment', 'url', 'lodash', 'q', 'jed', 'vumigo_v02', 'go-jsbox-metrics-helper', '@google-cloud/bigquery', 'seed-jsbox-utils'].indexOf(m) >= 0) return require(m); return null; }, Buffer: Buffer}"

rlimits:
  RLIMIT_DATA: [-1, -1] # 64 MB
  RLIMIT_STACK: [-1, -1] # 2 MB
  RLIMIT_AS: [-1, -1] # 1024 MB

sandbox:
  config:
    cls: vxsandbox.resources.config.FileConfigResource
    keys:
      config: /config/ussd_registration.json
      translation.eng.za: /config/go-app-ussd-registration.eng_ZA.json
      translation.zul.za: /config/go-app-ussd-registration.zul_ZA.json
      translation.sot.za: /config/go-app-ussd-registration.sot_ZA.json
  http:
    cls: vxsandbox.resources.http.HttpClientResource
  kv:
    cls: vxsandbox.resources.kv.RedisResource
    redis_manager:
      key_prefix: "vumi.jsbox.kv"
      host: "redis"
    keys_per_user: 550000
  outbound:
    cls: vxsandbox.resources.outbound.OutboundResource
  metrics:
    cls: vxsandbox.resources.metrics.MetricsResource
    metrics_prefix: "mcza"

# middleware configuration

middleware:
  - logging_mw: vumi.middleware.logging.LoggingMiddleware
  - unidecode_mw: vumi_unidecode_middleware.UnidecodeMiddleware


logging_mw:
  log_level: debug
