name: Docker Image CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get the version
        id: get_version
        run: |
          .ci/tag-from-ref.sh "${GITHUB_REF}"
      - name: Docker Build & Push
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: menconnect-jsbox
          tag: ${{ steps.get_version.outputs.TAG }}
          registry: hub.docker.com
          username: praekeltorgdeploy
          password: secrets.DOCKER_HUB_PASS
