name: Docker Image CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: |
          .ci/tag-from-ref.sh "${GITHUB_REF}"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
            praekeltfoundation/menconnect-jsbox
          tags: ${{ steps.get_version.outputs.TAG }}
      - uses: docker/setup-buildx-action@v1
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: praekeltorgdeploy
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
